version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: Adm!n123$
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

    ports:
      - '33060:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql