POST http://localhost:1664/api/v1/inventories
Content-Type: application/json

{
  "skuCode": "iPhone14",
  "quantity": "100"
}

###
G:ET http://localhost:1664/api/v1/inventories?skuCode=iPhone15&quantity=100


