spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: Adm!n123$
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:mysql://localhost:3306/inventory_service
    password: Adm!n123$
    user: root
    baseline-on-migrate: true
server:
  port: 1664

